name: Lighthouse Audit on Vercel

on:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: npm install -g lighthouse

      - name: Run Lighthouse on Vercel deployment
        run: |
          lighthouse https://portfolio-jos.vercel.app \
            --output html \
            --output-path ./lighthouse-report.html \
            --chrome-flags="--headless" \
            --quiet

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: lighthouse-report
          path: lighthouse-report.html


# name: Lighthouse Audit Vercel deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   audit:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Run Lighthouse on Vercel
#         run: |
#           npx lighthouse https://portfolio-jos.vercel.app \
#             --output html \
#             --output-path ./lighthouse-report.html \
#             --quiet \
#             --chrome-flags="--headless"

#       - name: Upload Lighthouse Report
#         uses: actions/upload-artifact@v3.1.2
#         with:
#           name: lighthouse-report
#           path: lighthouse-report.html
