name: Lighthouse Audit Vercel deploy

on:
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Run Lighthouse on Vercel
        run: |
          npx lighthouse https://portfolio-jos.vercel.app \
            --output html \
            --output-path ./lighthouse-report.html \
            --quiet \
            --chrome-flags="--headless"

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: lighthouse-report.html
