name: Lighthouse Audit on Vercel

on:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_SUPABASE_ROLE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ROLE_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

    steps:
      - name: Install dependencies
        run: npm install -g lighthouse

      - name: Run Lighthouse on Vercel deployment
        run: |
          lighthouse https://portfolio-jos.vercel.app \
            --output html \
            --output-path ./lighthouse-report.html \
            --chrome-flags="--headless" \
            --quiet

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: lighthouse-report
          path: lighthouse-report.html

# a
# name: Lighthouse Audit Vercel deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   audit:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Run Lighthouse on Vercel
#         run: |
#           npx lighthouse https://portfolio-jos.vercel.app \
#             --output html \
#             --output-path ./lighthouse-report.html \
#             --quiet \
#             --chrome-flags="--headless"

#       - name: Upload Lighthouse Report
#         uses: actions/upload-artifact@v3.1.2
#         with:
#           name: lighthouse-report
#           path: lighthouse-report.html
